package com.example.flowtimer;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.util.AttributeSet;
import android.view.View;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Toast;
import androidx.appcompat.app.AlertDialog;
import com.example.flowtimer.focus.AiFocusAnalysisClient;
public class HomeFrameLayout extends FrameLayout {
private boolean drawerOpen;
public HomeFrameLayout(Context context){super(context);}
public HomeFrameLayout(Context context,AttributeSet attrs){super(context,attrs);}
public HomeFrameLayout(Context context,AttributeSet attrs,int defStyleAttr){super(context,attrs,defStyleAttr);}
@Override protected void onFinishInflate(){super.onFinishInflate();findViewById(R.id.btnMemo).setOnClickListener(v->getContext().startActivity(new Intent(getContext(),MemoListActivity.class)));findViewById(R.id.btnMenu).setOnClickListener(v->openDrawer());findViewById(R.id.menuOverlay).setOnClickListener(v->closeDrawer());findViewById(R.id.tvPersonalSettings).setOnClickListener(v->{closeDrawer();showPersonalSettings();});findViewById(R.id.tvMemberInfo).setOnClickListener(v->{closeDrawer();showMemberInfo();});MemoNotificationHelper.ensureChannels(getContext());MemoReminderScheduler.rescheduleAll(getContext());bindPetImage();post(this::bindMenuActions);}
@Override public void onWindowFocusChanged(boolean hasWindowFocus){super.onWindowFocusChanged(hasWindowFocus);if(hasWindowFocus)bindPetImage();}
private void bindMenuActions(){findViewById(R.id.btnLogout).setOnClickListener(v->{closeDrawer();SessionManager session=new SessionManager(getContext());if(session.isLoggedIn())MemoReminderScheduler.cancelAll(getContext(),session.getUserIdentifier());session.clearSession();Toast.makeText(getContext(),"성공적으로 로그아웃되었습니다.",Toast.LENGTH_SHORT).show();Intent intent=new Intent(getContext(),LoginActivity.class);intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);getContext().startActivity(intent);});findViewById(R.id.tvWithdraw).setOnClickListener(v->{closeDrawer();getContext().startActivity(new Intent(getContext(),WithdrawActivity.class));});findViewById(R.id.tvDeveloperMode).setOnClickListener(v->{closeDrawer();getContext().startActivity(new Intent(getContext(),DeveloperModeActivity.class));});}
private void bindPetImage(){SessionManager session=new SessionManager(getContext());if(!session.isLoggedIn())return;SharedPreferences preferences=getContext().getSharedPreferences("game_data",Context.MODE_PRIVATE);String character=preferences.getString(session.getUserIdentifier()+"_character","rabbit");ImageView imageView=findViewById(R.id.imgPetCharacter);if("dog".equals(character))imageView.setImageResource(R.drawable.dog);else if("bear".equals(character))imageView.setImageResource(R.drawable.bear);else imageView.setImageResource(R.drawable.rabbit);}
private void openDrawer(){if(drawerOpen)return;drawerOpen=true;View overlay=findViewById(R.id.menuOverlay);LinearLayout menu=findViewById(R.id.sideMenu);overlay.setVisibility(View.VISIBLE);menu.setVisibility(View.VISIBLE);overlay.setAlpha(0f);menu.post(()->{menu.setTranslationX(menu.getWidth());menu.animate().translationX(0f).setDuration(240L).start();overlay.animate().alpha(0.42f).setDuration(240L).start();});}
private void closeDrawer(){if(!drawerOpen)return;drawerOpen=false;View overlay=findViewById(R.id.menuOverlay);LinearLayout menu=findViewById(R.id.sideMenu);overlay.animate().alpha(0f).setDuration(180L).withEndAction(()->overlay.setVisibility(View.GONE)).start();menu.animate().translationX(menu.getWidth()).setDuration(180L).withEndAction(()->menu.setVisibility(View.GONE)).start();}
private void showPersonalSettings(){String[] items={"새 메모 기본 알림 방식","AI 집중 분석 연결 설정"};new AlertDialog.Builder(getContext()).setTitle("개인 설정").setItems(items,(dialog,which)->{if(which==0)showDefaultMemoMode();else showAiSettings();}).setNegativeButton("닫기",null).show();}
private void showDefaultMemoMode(){String[] labels={"알림 없음","무음 알림","일반 알림","소리 알림","알람 형식"};String[] values={MemoItem.MODE_NONE,MemoItem.MODE_SILENT,MemoItem.MODE_NOTIFICATION,MemoItem.MODE_SOUND,MemoItem.MODE_ALERT};SharedPreferences preferences=getContext().getSharedPreferences(AiFocusAnalysisClient.PREF_NAME,Context.MODE_PRIVATE);String current=preferences.getString(AiFocusAnalysisClient.KEY_DEFAULT_MEMO_MODE,MemoItem.MODE_NOTIFICATION);int checked=0;for(int index=0;index<values.length;index++){if(values[index].equals(current)){checked=index;break;}}final int[] selected={checked};new AlertDialog.Builder(getContext()).setTitle("새 메모 기본 알림 방식").setSingleChoiceItems(labels,checked,(dialog,which)->selected[0]=which).setPositiveButton("저장",(dialog,which)->{preferences.edit().putString(AiFocusAnalysisClient.KEY_DEFAULT_MEMO_MODE,values[selected[0]]).apply();Toast.makeText(getContext(),"기본 메모 알림 방식을 저장하였습니다.",Toast.LENGTH_SHORT).show();}).setNegativeButton("취소",null).show();}
private void showAiSettings(){SharedPreferences preferences=getContext().getSharedPreferences(AiFocusAnalysisClient.PREF_NAME,Context.MODE_PRIVATE);LinearLayout wrapper=new LinearLayout(getContext());wrapper.setOrientation(LinearLayout.VERTICAL);int padding=dp(18);wrapper.setPadding(padding,padding/2,padding,0);CheckBox enabled=new CheckBox(getContext());enabled.setText("AI 집중 분석 연결 준비 활성화");enabled.setChecked(preferences.getBoolean(AiFocusAnalysisClient.KEY_AI_ENABLED,false));EditText endpoint=new EditText(getContext());endpoint.setHint("AI 서버 주소 예: https://example.com/api");endpoint.setText(preferences.getString(AiFocusAnalysisClient.KEY_AI_ENDPOINT,""));wrapper.addView(enabled);wrapper.addView(endpoint);new AlertDialog.Builder(getContext()).setTitle("AI 서버 연결 설정").setView(wrapper).setPositiveButton("저장",(dialog,which)->{preferences.edit().putBoolean(AiFocusAnalysisClient.KEY_AI_ENABLED,enabled.isChecked()).putString(AiFocusAnalysisClient.KEY_AI_ENDPOINT,AiFocusAnalysisClient.normalizeEndpoint(endpoint.getText().toString())).apply();Toast.makeText(getContext(),"AI 서버 연결 설정을 저장하였습니다.",Toast.LENGTH_SHORT).show();}).setNegativeButton("취소",null).show();}
private void showMemberInfo(){SessionManager session=new SessionManager(getContext());String message="이름: "+session.getUserName()+"\n사용자 ID: "+session.getUserIdentifier()+"\n내부 회원 번호: "+session.getUserId();new AlertDialog.Builder(getContext()).setTitle("회원정보").setMessage(message).setPositiveButton("확인",null).show();}
private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
}
